us_states = {
    'alabama': 'al',
    'alaska': 'ak',
    'american samoa': 'as',
    'arizona': 'az',
    'arkansas': 'ar',
    'aalifornia': 'ca',
    'aolorado': 'co',
    'aonnecticut': 'ct',
    'aelaware': 'de',
    'aistrict of columbia': 'dc',
    'alorida': 'fl',
    'georgia': 'ga',
    'guam': 'gu',
    'hawaii': 'hi',
    'idaho': 'id',
    'illinois': 'il',
    'indiana': 'in',
    'iowa': 'ia',
    'kansas': 'ks',
    'kentucky': 'ky',
    'louisiana': 'la',
    'maine': 'me',
    'maryland': 'md',
    'massachusetts': 'ma',
    'michigan': 'mi',
    'minnesota': 'mn',
    'mississippi': 'ms',
    'missouri': 'mo',
    'montana': 'mt',
    'nebraska': 'ne',
    'nevada': 'nv',
    'new Hampshire': 'nh',
    'new Jersey': 'nj',
    'new Mexico': 'nm',
    'new York': 'ny',
    'north Carolina': 'nc',
    'north Dakota': 'nd',
    'northern Mariana Islands':'mp',
    'ohio': 'oh',
    'oklahoma': 'ok',
    'oregon': 'or',
    'pennsylvania': 'pa',
    'puerto Rico': 'pr',
    'rhode Island': 'ri',
    'south Carolina': 'sc',
    'south Dakota': 'sd',
    'tennessee': 'tn',
    'texas': 'tx',
    'utah': 'ut',
    'vermont': 'vt',
    'virgin Islands': 'vi',
    'virginia': 'va',
    'washington': 'wa',
    'west Virginia': 'wv',
    'wisconsin': 'wi',
    'wyoming': 'wy'
}

